### PR TITLE
Add support for optional method parameter at login

### PR DESCRIPTION
**Pull request by pradtke**
See https://apereo.github.io/cas/5.0.x/protocol/CAS-Protocol-Specification.html#211-parameters

> method [OPTIONAL, CAS 3.0] - The method to be used when sending responses. While native HTTP redirects (GET) may be utilized as the default method, applications that require a POST response can use this parameter to indicate the method type. It is up to the CAS server implementation to determine whether or not POST responses are supported.

### CODE REVIEW

**Comment by tvdijen** [comment]
@pradtke I'd be happy to merge this, however your test fails...  Not sure it always has, but it did after rebasing against master today..  I mean, I can make 200 match 302 any day, but I would really know what I'm doing.. Could you have a look at this?

On a different note.. We've been working hard recently @ SSP to externalize most modules and find a 'curator' for them.. Since you're the only one actively posting issues & PR's here, would you be willing to take custody of this repository? We'll get you write-perms on the repo

**Comment by pradtke** [comment]
I'll take a look an updating the tests.
I'm also happy to take over as curator.  We have some customer requests for improvements that I think are generally available.  How does being curator work? would you still want to view PRs that I create? or would you prefer stepping back to focus on the main project?

**Comment by tvdijen** [comment]
I think a second pair of eyes never hurt, but feel free to merge if after a week or so nobody commented (like what happened with this PR).
Our main focus will be on the main project, but we like to try and keep a common standard across all the modules (think PSR-2, shorthand arrays, stuff like that).

**Comment by pradtke** [comment]
@tvdijen I finally figured out why it was failing.  The integration test runs the embedded php webserver, however it was pulling in the most recent release of `simplesamlphp-module-casserver` rather than the code in this branch so it wasn't picking up the change to `login.php`. I fixed that, and fixed a test that wasn't php 5.6 compatible.  

There ended up being a lot of noisy commits in this PR.  If you agree with the changes, then I think we should do a  'Squash and merge' to merge in the PR

**Comment by tvdijen** [comment]
Excellent work!

**Pull request merged**
